/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/U6Of5HHaZ9P
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <div className="bg-gradient-to-br from-pink-300 to-red-100 min-h-screen">
      <nav className="container mx-auto px-6 py-4 flex justify-between items-center">
        <div className="text-2xl font-bold text-red-600">Disney AI Poster Generator</div>
        <div className="space-x-4">
          <Link className="text-gray-700 hover:text-gray-900" href="#">
            Home
          </Link>
          <Link className="text-gray-700 hover:text-gray-900" href="#">
            Playground
          </Link>
          <Link className="text-gray-700 hover:text-gray-900" href="#">
            Pricing
          </Link>
          <Link className="text-gray-700 hover:text-gray-900" href="#">
            Blogs
          </Link>
        </div>
        <Button variant="outline">Log in</Button>
      </nav>
      <section className="container mx-auto px-6 py-12">
        <div className="flex flex-col lg:flex-row items-center">
          <div className="lg:w-1/2">
            <Badge className="mb-4" variant="secondary">
              FEATURED ON Product Hunt 198
            </Badge>
            <h1 className="text-5xl font-bold text-gray-800 mb-6">
              Turn your pet or photo into a Disney Pixar character
            </h1>
            <p className="text-gray-600 mb-6">
              Turn your pets into a stunning piece of disney pixar character. Get started today and transform your
              photos into breathtaking creations!
            </p>
            <div className="flex space-x-4">
              <Button>Get started for free</Button>
              <Link className="text-red-500 hover:text-red-700" href="#">
                Learn more →
              </Link>
            </div>
          </div>
          <div className="lg:w-1/2 mt-8 lg:mt-0 flex flex-wrap justify-center gap-4">
            <Card className="w-[200px]">
              <CardContent>
                <img
                  alt="Dog in Santa Outfit"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
              </CardContent>
            </Card>
            <Card className="w-[200px]">
              <CardContent>
                <img
                  alt="Happy Dog"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
              </CardContent>
            </Card>
            <Card className="w-[200px]">
              <CardContent>
                <img
                  alt="Disney Princess"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
              </CardContent>
            </Card>
            <Card className="w-[200px]">
              <CardContent>
                <img
                  alt="Girl in Santa Hat"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}
